### ISSUE TITLE
is this project open? like can i learn from it or not. Please reply back

### ISSUE THREAD

**Issue by faisalmushtaq007** [heeyunlee/cccc#3]

**Comment by heeyunlee** [comment]
Hello Faisal, this project is something I started/worked on when I was still a student, which is more than a year ago now. While it is still "open" and I worked on minor improvements here and there since then, this repo is pretty old and outdated. I am planning on updating this repo with the up-to-date practices, but if you can be more specific on what you want to learn from this repo, I'll try to answer you

**Comment by faisalmushtaq007** [comment]
@heeyunlee sir i have to implement plaid_flutter in one of my apps. I have no idea about it

**Comment by heeyunlee** [comment]
Well, a good starting point is reading all the available docs, like [plaid_flutter](https://pub.dev/packages/plaid_flutter) and [Plaid Link](https://plaid.com/docs/link/). Don't forget that you need some kind of server/backend service so that you can make an authentication request and retrieve a token. In my case, I just used GCP's [Cloud Function](https://cloud.google.com/functions) with Python. I hope this helps

**Comment by faisalmushtaq007** [comment]
Can you please send me  .zip of your project?  I thought I'll run this project and will check how it works

**Comment by heeyunlee** [comment]
The entire project is available right here, on this repo. I don't know why you're asking for a `.zip` file. Unless you have a valid question/issue, I'm going to have to close this issue.

**Comment by faisalmushtaq007** [comment]
I am not able to run it, because it's lacking the google service files., because of git ignore file

**Comment by heeyunlee** [comment]
Faisal, those files were obviously ignored because they contain private keys. You can configure Firebase yourself to generate those files. I will try to update readme with instructions, but in the meantime, read some publicly available documentations...
